### ISSUE TITLE
Hey, great work, thanks!

### ISSUE THREAD

**Issue by pliu19** [koren-v/Interpret#4]
Hello, thanks for the work. May I ask if you have your articl somewhere else? It seems the article you linked requires pay wall. Thanks!

**Comment by koren-v** [comment]
Hi @pliu19, thanks!
Didn't think that medium makes the articles paid on its own (I didn't do any special things to make it paid). But try to open in incognito, usually works)

**Comment by pliu19** [comment]
Thanks! Incognito saves my life!
